[project]
name = "plotly-interactive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "nbformat>=5.10.4",
    "numpy>=2.3.5",
    "plotly>=6.5.0",
    "scipy>=1.16.3",
]
